sudo: required
language: python
services:
- docker
before_install:
- docker pull smintz/nomadgen-builder
install:
- pip install --upgrade pycodestyle
script:
- docker run --privileged -v /home/travis/build/smintz/nomadgen:/work smintz/nomadgen-builder
  /bin/bash -c "cd /work; pip install setuptools && make deps && make test"
- pycodestyle --exclude=constants.py,ttypes.py nomadgen
- docker run --privileged -v /home/travis/build/smintz/nomadgen:/work smintz/nomadgen-builder
  /bin/bash -c "cd /work; pip install setuptools && make deps && make pex"
deploy:
  provider: releases
  api_key:
    secure: oyApEpX5WpaqHTcKfBmdT48N2ACwxnkZxCX0Ohb56Ec9e8S7h9BXoxo8HbsHcCUlJicflwQv50nXjB0du/iVOBc0IwKSDRUn4L7Go7JayzsZ8yoG9v5eX6fVpF90F1Ing+Rb2+gJmSA1WlgpH7ZSBvPIVnWzSn/V1/LHo5B32BE8ijUlJMNvVjilPwy8Y88+AsWJ5TBBQKitgzq2a9WiRe+8rFyakZit5ifXm2Nat2AylkRQz2opfTuQfH5ZC+Z1CJGRyuFWEkwDrYQAXiQNpomXkPANBSmrk2rMiCExgfLzFggz729E0uJjOxWfltyQeruoo7qachb0lCp1Nq6pNqrRtSKOsa5R85Quz0atk0fA8XejbTV/7aFrc//t8OdE/3K9hFC4mdRs53T8+9wOhE7UKrxish8uiSVGrY1HQr4f8pI9G3UbRm8QGa03aSPgt4KbYDQT7NSDvcX14lfefqSFo+g3CL2DorNoXviwb76stMMNfNw57y2RP7j1wTivioFlC5HCbjRmhz4OMDRC1ELcPN/RZuD3ypQpXVA+d02zNb+N0ql1bfxUMdZYrdfXiM+bhvPVR9O4CiGFrOHNwJRwzJk0NyLpnXnS/MBeWs+iX/Ul6slfCIr2JEgx8MQK+gkbRQ2kt+vakfbrGg6OYujByVfkCnE+LUrpQOKHsPE=
  file: ./build/nomadgen.pex
  on:
    tags: true
