sudo: required

language: python

services:
  - docker

before_install:
  - docker run -v $(pwd):/work /bin/bash smintz/nomadgen-builder -c "cd /work; pip install setuptools && make deps && make"

script:
  - make
