sudo: required
language: python
addons:
  homebrew:
    packages:
      - mstch
      - folly
      - bison
matrix:
  include:
    - os: linux
      dist: xenial
      python: 2.7
      env: TOXENV=py27
    - os: linux
      dist: xenial
      python: 3.6
      env: TOXENV=py36
    - os: osx
      python: 2.7
      env: TOXENV=py27
    - os: osx
      python: 3.7
      env: TOXENV=py37
install:
- pip install --upgrade pycodestyle
- ./.travis/install.sh
script:
  - make test
  - make pex
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "XqRjMtM56AZyLG/iLSww8bql3biX0YGqZWLpznh0Vqf+Y0fiQebspLIWo30cgWqNax4n+HMtAK3D2e8bFu2YUJt823J97jOKWJqpFlWgAunEQwHpxzj+xU2qo3xozYb7ESnqjaDEuD99gMNK4JB6eOCLykHF0hO5ERiilGVq69r/x3tKz7ePnIiSM/f1Cin1sg9Cl26QTpRlNjKBZfMb0j9Fhkph8THJWDI7UvDBwncgANvO/46m5x9L3MZKDLxH8XQoMZPEThwXPYyOH4pN897xEVKpkksScEU6MfGsgqIz4c1jBvfomvhVB+qA55xdKb6XfhynB7yD45ATX3sCSGCQXL/zJcgudzOJxeVpUrKsXM6jhGlg06CeiAASqtbl0TOs2NghSEwd3PWMhqQsDKL6g7gIfTmJBJNsVFAZgDXmb01uXHXhSnrJy5YqgK4A9KwVl4KNSqK4HLHkwtVLJ/lazAGIjHkebkkCr9PTqDgAhowGcSKsUBA33edS5J9L9qqolHRLe7VBnPikFc1pj52aXcurvzDg3AD1V9bnrnsyn4jhs0yEur3lSOuYwkfr/XO4YhUsET2gmaKV+jaImE2zy/d4r+pVtye1or5GgT+dOhh7c3n7POUsq1IgeD21HK3dFA/GbiHOg6re71h/ajQU/7vjQERnfS5J/hgiQjQ="
  file_glob: true
  file: "./build/*"
  on:
    tags: true
