sudo: required

language: python

services:
  - docker

before_install:
  - docker run smintz/nomadgen-builder -v $(pwd):/work /bin/bash -c "cd /work; pip install setuptools && make deps && make"

script:
  - make
